// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/14/2026, 10:22:43 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/kevin/Projects/convene-the-council/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevin/Projects/convene-the-council/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevin/Projects/convene-the-council/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevin/Projects/convene-the-council/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevin/Projects/convene-the-council/plugins/**/*.{js,ts,mjs}","/Users/kevin/Projects/convene-the-council/composables/**/*.{js,ts,mjs}","/Users/kevin/Projects/convene-the-council/utils/**/*.{js,ts,mjs}","/Users/kevin/Projects/convene-the-council/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevin/Projects/convene-the-council/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kevin/Projects/convene-the-council/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kevin/Projects/convene-the-council/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;